spring:
  application:
    name: auth-service

  security:
    user:
      name: tapajyoti
      password: 123456


  datasource:
    url: jdbc:postgresql://localhost:5432/intellitex_auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
